### ISSUE TITLE
Update Plugin to work with both Mac OS High Sierra 10.13.1 and earlier versions

### ISSUE THREAD

**Issue by guofoo** [Live4Code/Sketch2App#7] opened 2017-11-28 23:42 UTC
Currently the plugin does not seem to work on High Sierra systems.

<img width="952" alt="screen shot 2017-11-22 at 3 08 11 pm" src="https://user-images.githubusercontent.com/742628/33350256-b32fc880-d452-11e7-838a-9c915e93377e.png">

**Comment by meticulous-dft** [comment] 2017-11-29 07:36
This is caused by cocoa script [issue](https://github.com/ccgus/CocoaScript/issues/48). The two functions used stop working for high sierra. 

This is fixed in 7ae930a. Basically use JSON object instead of NSObject, and change from `NSArray.arrayWithObject_` to `NSArray.arrayWithArray_` as pointed out in the above issue.

**Closed as completed by meticulous-dft** 2017-11-29 07:36 UTC
